feat: prescription search functionalities added

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,30 +1,73 @@
+# #!/bin/bash
+
+# printf "\n---------------Running git pre-commit hook---------------\n"
+
+# ## this will retrieve all of the .go files that have been
+# ## changed since the last commit
+# STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep '.go$')
+
+# ## we can check to see if this is empty
+# if [[ $STAGED_GO_FILES == "" ]]; then
+#     printf "No Go Files to Update!\n"
+# else
+#     for FILE in $STAGED_GO_FILES; do
+#         go fmt "$FILE"
+#         "$(go env GOPATH)"/bin/goimports -w "$FILE"
+#     done
+
+#     "$(go env GOPATH)"/bin/golangci-lint run
+#     if [[ $? != 0 ]]; then
+#         printf "\nCommit failed! Please fix errors before committing.\n"
+#         exit 1
+#     fi
+
+#     for FILE in $STAGED_GO_FILES; do
+#         git add "$FILE"
+#     done
+# fi
+
+
+# printf "\n---------------Git pre-commit hook end---------------\n"
+
+
 #!/bin/bash
 
 printf "\n---------------Running git pre-commit hook---------------\n"
 
-## this will retrieve all of the .go files that have been
-## changed since the last commit
+# 1. Retrieve all .go files staged for commit from the root
+# This will now include the 'backend/' prefix in the file paths
 STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep '.go$')
 
-## we can check to see if this is empty
 if [[ $STAGED_GO_FILES == "" ]]; then
     printf "No Go Files to Update!\n"
 else
+    # Get GOPATH once to avoid repeated calls in the loop
+    GOPATH=$(go env GOPATH)
+
     for FILE in $STAGED_GO_FILES; do
+        # Format the file
         go fmt "$FILE"
-        "$(go env GOPATH)"/bin/goimports -w "$FILE"
+        
+        # Run goimports
+        # Added a check to ensure goimports exists to prevent script failure
+        if [ -f "$GOPATH/bin/goimports" ]; then
+            "$GOPATH/bin/goimports" -w "$FILE"
+        else
+            printf "Warning: goimports not found at $GOPATH/bin/goimports\n"
+        fi
+        
+        # Re-stage the formatted file
+        git add "$FILE"
     done
 
-    "$(go env GOPATH)"/bin/golangci-lint run
+    # 2. Run golangci-lint
+    # We run this from the root; golangci-lint usually finds the 
+    # nested go.mod in the backend folder automatically.
+    printf "Running golangci-lint...\n"
+    "$GOPATH"/bin/golangci-lint run ./backend/...
+
     if [[ $? != 0 ]]; then
         printf "\nCommit failed! Please fix errors before committing.\n"
         exit 1
     fi
-
-    for FILE in $STAGED_GO_FILES; do
-        git add "$FILE"
-    done
 fi
-
-
-printf "\n---------------Git pre-commit hook end---------------\n"
